---

name: Packer

on: workflow_dispatch

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@master

      - run: |
          [[ -f ${{github.workspace }}/raspberry-spi  ]] && cd raspberry-spi
          ls -la
          pwd
          
      - run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build raspberry-spi/pi-imager/raspios.json

      - run: ls -la ${{ github.workspace }}/raspberry-spi

      - run: |
          ls -la
          pwd
          tar -czvf raspberry-spi/custom-raspios-arm.tar.gz custom-raspios-arm.img
          pwd
          ls -la

      - id: tag 
        run: |
          cd ${{ github.workspace }}/raspberry-spi
          TAG="custom-$(./pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          echo ::set-output name=TAG::${TAG}

      - run: echo "${{ steps.tag.outputs.TAG }}" >> release.md

      - uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ steps.tag.outputs.TAG }}
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: add image to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/raspberry-spi/custom-raspios-arm.tar.gz
          asset_name: custom-raspios-arm.tar.gz
          asset_content_type: application/gzip