---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:

      - run: pwd

      - name: Checkout packer-builder-arm
        uses: actions/checkout@master
        with:
          repository: mkaczanowski/packer-builder-arm
          ref: master

      - run: pwd

      - name: Build packer-builder-arm
        run: |
          pwd
          ls -la
          go version
          go mod download
          go build

      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          path: raspberry-spi

      - run: |
          ls -la
          pwd
          echo $PACKER_HOME_DIR

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: raspberry-spi/pi-imager/raspios.json 
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts