---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:

      - run: pwd

      - name: Checkout packer-builder-arm
        uses: actions/checkout@master
        with:
          repository: mkaczanowski/packer-builder-arm
          ref: master

      - run: pwd

      - name: Build packer-builder-arm
        run: |
          pwd
          ls -la
          go version
          go mod download
          go build

      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          path: raspberry-spi

      - run: |
          ls -la
          pwd
          echo $PACKER_HOME_DIR
          
      - run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build raspberry-spi/pi-imager/raspios.json

      - run: |
          ls -la
          pwd
          echo $PACKER_HOME_DIR