---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:

      - run: pwd

      - name: Checkout packer-builder-arm
        uses: actions/checkout@master
        with:
          repository: mkaczanowski/packer-builder-arm
          ref: master

      - run: pwd

      - name: Build packer-builder-arm
        run: |
          pwd
          ls -la
          go version
          go mod download
          go build

      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          path: raspberry-spi

      - run: |
          ls -la
          pwd
          
      - run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build raspberry-spi/pi-imager/raspios.json

      - run: |
          ls -la
          pwd
          echo $PACKER_HOME_DIR
          cd raspberry-spi
          TAG="custom-$(./pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          tar -czvf custom-raspios-arm.tar.gz ../custom-raspios-arm.img
      
      - uses: actions/upload-artifact@v2
        with:
          name: ${TAG}
          path: custom-raspios-arm.tar.gz

      - run: echo "custom raspios image" >> release.md

      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${TAG}
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}