---

name: RaspiOs ++

on: 
  workflow_dispatch:
    inputs:
      imageType:
        description: 'Type of image to create'     
        required: true
        default: 'docker-host' 
        type: choice
        options:
        - docker-host
        - ssh-enabled
        - kube-worker

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer Build  

    steps:
      - name: Install moreutils
        run: sudo apt-get update -y && sudo apt-get install -y moreutils

      - name: Checkout Repository
        uses: actions/checkout@master  

      - name: Packer Build
        env:
          TEMPLATE: ${{ github.event.inputs.imageType }}
        run: |
          cd pi-imager
          ./fetch-image.sh -b templates/${TEMPLATE}.json
          cd ..
      
      - name: Compress Image
        run: tar -czvf custom-raspios-arm.tar.gz pi-imager/custom-raspios-arm.img

      - name: Create Release Tag
        id: tag 
        run: |
          TAG="custom-$(./pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          echo ::set-output name=TAG::${TAG}

      - name: Update Release Notes
        run: echo "${{ steps.tag.outputs.TAG }}" >> release.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ steps.tag.outputs.TAG }}
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/custom-raspios-arm.tar.gz
          asset_name: custom-raspios-arm.tar.gz
          asset_content_type: application/gzip