---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:

      - run: pwd

      - name: Checkout packer-builder-arm
        uses: actions/checkout@master
        with:
          repository: mkaczanowski/packer-builder-arm
          ref: master

      - run: pwd

      - name: Build packer-builder-arm
        run: |
          pwd
          ls -la
          go version
          go mod download
          go build

      - name: Checkout Repository
        uses: actions/checkout@master
        with:
          path: raspberry-spi

      - run: |
          ls -la
          pwd
          
      - run: docker run --rm --privileged -v /dev:/dev -v ${PWD}:/build mkaczanowski/packer-builder-arm build raspberry-spi/pi-imager/raspios.json


      - run: ls -la ${{ github.workspace }}/raspberry-spi

      - run: |
          ls -la
          pwd
          tar -czvf raspberry-spi/custom-raspios-arm.tar.gz custom-raspios-arm.img
          pwd
          ls -la

      - uses: actions/upload-artifact@v3
        with:
          name: os-image
          path: ${{ github.workspace }}/raspberry-spi/custom-raspios-arm.tar.gz

      - id: tag 
        run: |
          cd ${{ github.workspace }}/raspberry-spi
          TAG="custom-$(./pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          echo ::set-output name=TAG::${TAG}

      - run: echo "${{ steps.tag.outputs.TAG }}"

      # - run: echo "custom raspios image" >> release.md

      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: ${{ steps.tag.outputs.TAG }}
      #     tag: ${{ steps.tag.outputs.TAG }}
      #     bodyFile: "release.md"
      #     token: ${{ secrets.GITHUB_TOKEN }}