name: Build Image
on:
  workflow_call:
    inputs:
      imageType:
        required: true
        type: string

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer Build  

    steps:
      - name: Install moreutils
        run: sudo apt-get update -y && sudo apt-get install -y moreutils

      - name: Checkout Repository
        uses: actions/checkout@master  

      - name: Packer Build
        env:
          TEMPLATE: ${{ github.event.inputs.imageType }}
        run: |
          cd pi-imager
          ./fetch-image.sh -b templates/${TEMPLATE}.json
          cd ..
      
      - name: Compress Image
        run: tar -czvf custom-raspios-arm.tar.gz pi-imager/custom-raspios-arm.img

      - name: Tag Artifact
        id: tag 
        run: |
          TAG="${{ github.event.inputs.imageType }}-$(./pi-imager/fetch-image.sh -v)"
          echo ::set-output name=TAG::${TAG}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tag.outputs.TAG }}
          path: pi-imager/custom-raspios-arm.img
