---

name: Packer

on:
  push:

jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:

      - name: Checkout Repository
        uses: actions/checkout@master
        path: raspberry-spi

      - name: Checkout packer-builder-arm
        uses: actions/checkout@master
        with:
          repository: mkaczanowski/packer-builder-arm
          ref: master

      - name: Build packer-builder-arm
        run: |
          ls -la
          go version
          go mod download
          go build

      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: raspberry-spi/pi-imager/raspios.json

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: raspberry-spi/pi-imager/raspios.json

      # build artifact
      - name: Build Artifact
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: raspberry-spi/pi-imager/raspios.json 
        env:
          PACKER_LOG: 1

      # additional steps to process artifacts