name: Build Image
on:
  workflow_call:
    inputs:
      imageType:
        required: true
        type: string

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Packer Build  

    steps:
      - name: Install moreutils and xz-utils
        run: sudo apt-get update -y && sudo apt-get install -y moreutils xz-utils

      - name: Checkout Repository
        uses: actions/checkout@master  

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Packer Build
        run: |
          echo  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker pull ghcr.io/mbmcmullen27/raspberry-pi-images:latest
          docker run \
              --privileged=true \
              -v /dev:/dev \
              -v $(pwd)docker/src:/home/builder/src \
              -e script=${{ inputs.imageType }} \
              ghcr.io/mbmcmullen27/raspberry-pi-images:latest
          cd ..
      
      - name: Compress Image
        run: tar -czvf custom-raspios-arm.tar.gz docker/src/custom-raspios-arm.img

      - name: Tag Artifact
        id: tag 
        run: |
          TAG="${{ inputs.imageType }}-$(./pi-imager/fetch-image.sh -v)"
          echo ::set-output name=TAG::${TAG}

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.tag.outputs.TAG }}
          path: custom-raspios-arm.tar.gz
