name: Release Images
on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Create Release Tag
        id: tag 
        run: |
          TAG="custom-$(raspbery-spi/pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          echo ::set-output name=TAG::${TAG}

      - name: Update Release Notes
        run: echo "Docker, ssh enabled, and kube node variants of ${{ steps.tag.outputs.TAG }}" >> release.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ steps.tag.outputs.TAG }}
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: find
        run: find .

      - name: Attach Images to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/custom-raspios-arm.tar.gz
          asset_name: custom-raspios-arm.tar.gz
          asset_content_type: application/gzip