name: Release Images
on:
  workflow_call:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master  

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v2
        with:
          path: images/

      - name: find
        run: find .

      - name: Get Names
        id: get_paths
        run: |
          SSH_PATH=$(ls images/ssh*/custom-raspios-arm.tar.gz)
          DOCKER_PATH=$(ls images/docker*/custom-raspios-arm.tar.gz)
          KUBE_PATH=""
          echo ::set-output name=SSH_PATH::${SSH_PATH}
          echo ::set-output name=DOCKER_PATH::${DOCKER_PATH}
          echo ::set-output name=KUBE_PATH::${KUBE_PATH}

      - name: Create Release Tag
        id: tag 
        run: |
          TAG="custom-$(pi-imager/fetch-image.sh -v)"
          git tag $TAG 
          git push origin $TAG
          echo ::set-output name=TAG::${TAG}

      - name: Update Release Notes
        run: echo "Docker, ssh enabled, and kubernetes node variants of ${{ steps.tag.outputs.TAG }}" >> release.md

      - name: Create Release
        uses: ncipollo/release-action@v1
        id: create_release
        with:
          tag: ${{ steps.tag.outputs.TAG }}
          bodyFile: "release.md"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Attach SSH Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:  ${{ steps.get_paths.outputs.SSH_PATH }}
          asset_name: raspios-ssh-enabled.tar.gz
          asset_content_type: application/gzip

      - name: Attach Docker Image to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path:  ${{ steps.get_paths.outputs.DOCKER_PATH }}
          asset_name: raspios-docker-host.tar.gz
          asset_content_type: application/gzip